### ISSUE TITLE
ttf-droid_git.bb can fail

### ISSUE THREAD

**Issue by fmhess** [openembedded/meta-openembedded#104]
I somehow got my build into a state where ttf-droid_git.bb would fail in do_install_prepend() due to it trying to rm files that had already been deleted.  Changing "rm" to "rm -f" would be a workaround, although deleting files from the source directory in do_install_prepend seems like a hack in the first place.

**Comment by kraj** [comment]
this 390498950f16e177043e8bf55696fff7db9f63aa should fix it. if not please re-open
