### ISSUE TITLE
vlc build failure configure: error: libavutil versions 55 and later are not supported.

### ISSUE THREAD

**Issue by ibaldachini** [openembedded/meta-openembedded#119]
vlc 2.2.2 incompatible with ffmpeg 3.4.2

**Comment by kraj** [comment]
@ibaldachini  OE-Core now has 4.0.2, so its tested usually with the version from OE-core, however, if you provide more information on what errors you are seeing, we might be able to help

**Comment by ibaldachini** [comment]
If I enable libav in loca.conf

PACKAGECONFIG_pn-vlc_append = " libva"

then vlc does not build (it needs oldes ffmpeg version)

**Comment by kraj** [comment]
OK I think we need to upgrade this recipe to 3.x

**Comment by kraj** [comment]
fixed via da34efdc4670ff1fbaab715e2a36ae1cc120021f
