### ISSUE TITLE
ttf-arphic-uming has bogus LIC_FILES_CHKSUM

### ISSUE THREAD

**Issue by fmhess** [openembedded/meta-openembedded#126]
meta-openembedded/meta-oe/recipes-graphics/ttf-fonts/ttf-arphic-uming_20080216.bb

has a bogus LIC_FILES_CHKSUM that points at the README.  It should be something like

LIC_FILES_CHKSUM = "file://license/english/ARPHICPL.TXT;md5=4555ed88e9a72fc9562af379d07c3350"

**Comment by kraj** [comment]
I think this is a good improvement.

**Comment by kraj** [comment]
fixed with 70ccd088eac1ebf45d53b2d0fc9ac211a3905ade
