### ISSUE TITLE
xfsprogs: Do not support riscv

### ISSUE THREAD

**Issue by tuanha-viosoft** [openembedded/meta-openembedded#127]
I build xfsprogs for riscv and got error:
$ bitbake xfsprogs
Parsing recipes: 100% |###############################################################| Time: 0:00:15
Parsing of 2249 .bb files complete (0 cached, 2249 parsed). 3314 targets, 127 skipped, 0 masked, 0 er
rors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.40.0"  
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "riscv64-oe-linux"
MACHINE              = "qemuriscv64"
DISTRO               = "nodistro"
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "riscv64 littleendian"
meta                 = "master:c31bcb0555ae77fcb59c4d0798ec66bb27f63dc2"
meta-oe
meta-multimedia
meta-python
meta-networking
meta-filesystems     = "master-next:90956db4f410b162acb1468b93ebfc86786c4816"
meta-riscv           = "work:5b35295781cdfd255ef16b04073f182feffe5a0e"
...
| checking build system type... x86_64-pc-linux-gnu
| checking host system type... Invalid configuration `riscv64-oe-linux': machine `riscv64-oe' not recognized
| configure: error: /bin/bash ./config.sub riscv64-oe-linux failed
| NOTE: The following config.log files may provide further information.
| NOTE: /home/ubuntu/riscv-yocto/build/tmp-glibc/work/riscv64-oe-linux/xfsprogs/4.18.0-r0/xfsprogs-4.18.0/config.log
| ERROR: configure failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /home/ubuntu/riscv-yocto/build/tmp-glibc/work/riscv64-oe-linux/xfsprogs/4.18.0-r0/temp/log.do_configure.16645)
ERROR: Task (/home/ubuntu/riscv-yocto/meta-openembedded/meta-filesystems/recipes-utils/xfsprogs/xfsprogs_4.18.0.bb:do_configure) failed with exit code '1'

**Comment by kraj** [comment]
This is fixed and currently on master-next, so please use master-next branch for now, it will soon be in master
