### ISSUE TITLE
upstream bug in gtkmm 2.24.3

### ISSUE THREAD

**Issue by joshuaimmanuel** [openembedded/meta-openembedded#13]
The gtkmm version 2.24.3 has an upstream bug which will cause the compilation of applications which use gtkmm to break.

https://bugzilla.gnome.org/show_bug.cgi?id=697835

So, upgrading the gtkmm recipe in meta-oe layer to 2.24.4 solves the problem, there are no dependency changes when bumping the version to 2.24.4

**Comment by shr-project** [comment]
We don't use github.com for tracking issues.

If the issue is still valid, then send a patch to openembedded-devel@lists.openembedded.org
