### ISSUE TITLE
Netkit-ftp build failing - TI Processor SDK 05.03

### ISSUE THREAD

**Issue by prateek-khatri** [openembedded/meta-openembedded#139]
> prateekkhatri@PC-10307:~/work/tisdk/build$ MACHINE=am65xx-evm bitbake netkit-ftp
> WARNING: You have included the meta-virtualization layer, but 'virtualization' has not been enabled in your DISTRO_FEATURES. Some bbappend files may not take effect. See the meta-virtualization README for details on enabling virtualization support.
> Loading cache: 100% |###########################################################################################################################################################################| Time: 0:00:01
> Loaded 4234 entries from dependency cache.
> Parsing recipes: 100% |#########################################################################################################################################################################| Time: 0:00:13
> Parsing of 3309 .bb files complete (3306 cached, 3 parsed). 4237 targets, 523 skipped, 0 masked, 0 errors.
> WARNING: No recipes available for:
>   /home/prateekkhatri/work/tisdk/sources/meta-processor-sdk/recipes-devtools/python/python3-native_3.5.2.bbappend
>   /home/prateekkhatri/work/tisdk/sources/meta-processor-sdk/recipes-ti/devtools/ti-cgt-arm-native_16.9.2.bbappend
> NOTE: Resolving any missing task queue dependencies
> 
> Build Configuration:
> BB_VERSION           = "1.36.0"
> BUILD_SYS            = "x86_64-linux"
> NATIVELSBSTRING      = "ubuntu-18.04"
> TARGET_SYS           = "aarch64-linux"
> MACHINE              = "am65xx-evm"
> DISTRO               = "arago"
> DISTRO_VERSION       = "2018.10"
> TUNE_FEATURES        = "aarch64"
> TARGET_FPU           = ""
> meta-processor-sdk   = "HEAD:f33a37ac6baa8155302fa1faea99f1be5461779e"
> meta-ros             = "HEAD:e2566402ab108a19634354a934788109422cf409"
> meta-arago-distro    
> meta-arago-extras    = "HEAD:d4bc00af838df7a77f4ddbd3546755c5bad5b880"
> meta-browser         = "HEAD:26d50665e2f7223c5f4ad7481a8d2431e7cb55fb"
> meta-qt5             = "HEAD:d8b531530fa42b59aa0a5b123d87a30d749cbcc4"
> meta-virtualization  = "HEAD:b704c689b67639214b9568a3d62e82df27e9434f"
> meta-networking      
> meta-python          
> meta-oe              
> meta-gnome           
> meta-multimedia      
> meta-filesystems     = "HEAD:eae996301d9c097bcbeb8046f08041dc82bb62f8"
> meta-ti              = "HEAD:02e852b1a069463f937ea594e13fe5f88ce9b74d"
> meta-linaro-toolchain 
> meta-optee           = "HEAD:cd9ee776044a2d8943be4cb019f063271e9c684d"
> meta-updater         = "dev/ti:559dc9f7c3fa918e60e35b74ecebd4f0e652d5e4"
> meta-updater-ti      = "master:87f96945524ad1884db9e1347701b78e99380a02"
> meta                 = "HEAD:3638cb32ba9ba32b4d498fc31ab7fdf82f0d2495"
> 
> Initialising tasks: 100% |######################################################################################################################################################################| Time: 0:00:01
> NOTE: Executing SetScene Tasks
> NOTE: Executing RunQueue Tasks
> ERROR: netkit-ftp-0.17-r0 do_configure: oe_runmake failed
> ERROR: netkit-ftp-0.17-r0 do_configure: Function failed: autotools_preconfigure (log file is located at /home/prateekkhatri/work/tisdk/build/arago-tmp-external-linaro-toolchain/work/aarch64-linux/netkit-ftp/0.17-r0/temp/log.do_configure.13258)
> ERROR: Logfile of failure stored in: /home/prateekkhatri/work/tisdk/build/arago-tmp-external-linaro-toolchain/work/aarch64-linux/netkit-ftp/0.17-r0/temp/log.do_configure.13258
> Log data follows:
> | DEBUG: SITE files ['endian-little', 'bit-64', 'arm-common', 'arm-64', 'common-linux', 'common-glibc', 'aarch64-linux', 'common']
> | DEBUG: Executing shell function autotools_preconfigure
> | NOTE: make clean
> | (cd  ftp && make clean)
> | make[1]: Entering directory '/home/prateekkhatri/work/tisdk/build/arago-tmp-external-linaro-toolchain/work/aarch64-linux/netkit-ftp/0.17-r0/netkit-ftp-0.17/ftp'
> | Makefile:3: ../MCONFIG: No such file or directory
> | make[1]: *** No rule to make target '../MCONFIG'.  Stop.
> | make[1]: Leaving directory '/home/prateekkhatri/work/tisdk/build/arago-tmp-external-linaro-toolchain/work/aarch64-linux/netkit-ftp/0.17-r0/netkit-ftp-0.17/ftp'
> | Makefile:13: recipe for target 'ftp.clean' failed
> | make: *** [ftp.clean] Error 2
> | ERROR: oe_runmake failed
> | WARNING: /home/prateekkhatri/work/tisdk/build/arago-tmp-external-linaro-toolchain/work/aarch64-linux/netkit-ftp/0.17-r0/temp/run.autotools_preconfigure.13258:1 exit 1 from 'exit 1'
> | ERROR: Function failed: autotools_preconfigure (log file is located at /home/prateekkhatri/work/tisdk/build/arago-tmp-external-linaro-toolchain/work/aarch64-linux/netkit-ftp/0.17-r0/temp/log.do_configure.13258)
> ERROR: Task (/home/prateekkhatri/work/tisdk/sources/meta-openembedded/meta-networking/recipes-netkit/netkit-ftp/netkit-ftp_0.17.bb:do_configure) failed with exit code '1'
> NOTE: Tasks Summary: Attempted 1192 tasks of which 1187 didn't need to be rerun and 1 failed.
> 
> Summary: 1 task failed:
>   /home/prateekkhatri/work/tisdk/sources/meta-openembedded/meta-networking/recipes-netkit/netkit-ftp/netkit-ftp_0.17.bb:do_configure
> Summary: There were 2 WARNING messages shown.
> Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

Please advise.

**Comment by kraj** [comment]
you could try porting 02436486ba62ac6a4489eb2cc3428b140d9e8422 to this package
