### ISSUE TITLE
Missing pytest module 'importlib-metadata' after upgrade from 3.4.2 to 5.1.2

### ISSUE THREAD

**Issue by ckoppolu** [openembedded/meta-openembedded#144]
I have reached out to Chao, Yuan via the distribution list for a missing module in python's pytest upgrade from 3.4.2 to 5.1.1. The missing module was atomicwrites and a recipie was added to fix it. But, it is also missing 'importlib_metadata' which is required for pytest to run. Here is a link to all packages required by pytest:  https://github.com/pytest-dev/pytest/blob/master/setup.py#L10

Please provide a recipe for importlib_metadata and also any missing module's recipe. A better solution would be to test using pytest prior to upgrading it.

**Comment by kraj** [comment]
@ckoppolu please follow the discussion on mailing list with this info and see if Yuan can implement it
