### ISSUE TITLE
upower as systemd service might not start on zeus

### ISSUE THREAD

**Issue by Tragetaschen** [openembedded/meta-openembedded#158]
The upower package has received some "hardening" options in the systemd service unit. The `PrivateUsers=yes` one broke that package on my platform because it explicitly requires `CONFIG_USER_NS=y` in the kernel config

https://github.com/systemd/systemd/pull/5140

The service will attempt to start a couple of times before it's rate-limited.

**Comment by Tragetaschen** [comment]
Here's the relevant upower commit: https://cgit.freedesktop.org/upower/commit/src/upower.service.in?id=1c6a6bfbbb01aa92b4550c1e3a087b1c0f7ef310

**Comment by kraj** [comment]
thanks for noting it here. There should be a way to inform user about this option, perhaps a comment in systemd recipe could help.
