### ISSUE TITLE
gvfs 1.42 not in xfce arm64

### ISSUE THREAD

**Issue by rcla** [openembedded/meta-openembedded#166]
I build a minimum image of xfce for raspberry pi4 - 64 bit.

With the latest versions of the gvfs 1.42 package (1.42.1 or 1.42.2) of the master branch, on the desktop, mount and see other folders: pts, proc, run ... See attached image.

![screen_gvfs142](https://user-images.githubusercontent.com/45245617/71645439-9ab57d00-2ca6-11ea-9fe4-cb87d00bd1a6.jpg)

If I replace the gvfs package with the version of zeus branch 1.41.2, the desktop is fixed.

**Comment by kraj** [comment]
@schnitzeltony any ideas ?

**Comment by schnitzeltony** [comment]
No - have not yet seen this. From the icons shown it seems gvfs treats these folders as removable disks...
To analyse I would like to know @rcla:

* For me to reproduce What image do build exactly and what is your build configuration?
* With gvfs 1.42.x: start 'Settings Manager', select 'Desktop' and enter tab 'Icons'. In the bottom there is a list with 'Default Icons'. Which entries does this list contain? Start unchecking entries in this list. What entry has to be unchecked to let faulty icons disappear?

**Comment by rcla** [comment]
@schnitzeltony
> * For me to reproduce What image do build exactly and what is your build configuration?

Have the latest "master" branches, downloaded yesterday from:
```
poky
meta-raspberrypi
meta-openembedded
```

local.conf:
```
DISTRO_FEATURES_append = " opengl x11 polkit"
MACHINE ??= "raspberrypi4-64"
MACHINE_FEATURES_append = " vc4graphics"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_dev_manager = "systemd"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
```

Build: `core-image-minimal-xfce`


> * With gvfs 1.42.x: start 'Settings Manager', select 'Desktop' and enter tab 'Icons'. In the bottom there is a list with 'Default Icons'. Which entries does this list contain? Start unchecking entries in this list. What entry has to be unchecked to let faulty icons disappear?

removable devices: Other devices

Also, when you enter the Thunar, USB or Flash drive, it does not mount or display.
It does not detect them.

**Comment by rcla** [comment]
I attach a log file when using version gvfs 1.41.2 and when it fails with version gvfs 1.42.2.
[Logs.txt](https://github.com/openembedded/meta-openembedded/files/4021496/Logs.txt)

I see the following message:
`failed: Process org.gtk.vfs.UDisks2VolumeMonitor received signal 5`

**Comment by rcla** [comment]
I have solved the problem by installing:
`gvfs-dev`

For some reason in xfce, for gvfs versions 1.42.x to work correctly, gvfs-dev is required.

**Comment by schnitzeltony** [comment]
Hmm that sounds odd. Have 1.42.2 running here without issues and no -dev package installed. Wonder if it is related to 64 bit. Unfortunately I don't have the resources to test that now - build machine is busy...
