### ISSUE TITLE
python3-pycryptodome_3.9.4 does not have module named 'Cryptodome'

### ISSUE THREAD

**Issue by RajeshRavi-brcm** [openembedded/meta-openembedded#187]
meta-openembedded/meta-python/recipes-devtools/python/python3-pycryptodome_3.9.4.bb does not have Cryptodome.

I see error: "ModuleNotFoundError: No module named 'Cryptodome"
when I use DEPENDS += "python3-pycryptodome-native"  in optee_os recipe:

https://github.com/OP-TEE/optee_os/issues/3624

Interestingly, Cryptodome module is found in python counter part of the recipe: python-pycryptodomex_3.9.4.bb.

Log
-----
find tmp/ -path '*/Cryptodome/init.py'
tmp/work/x86_64-linux/python-pycryptodomex-native/3.9.4-r0/pycryptodomex-3.9.4/lib/Cryptodome/init.py
tmp/work/x86_64-linux/python-pycryptodomex-native/3.9.4-r0/pycryptodomex-3.9.4/build/lib.linux-x86_64-2.7/Cryptodome/init.py
tmp/work/x86_64-linux/python-pycryptodomex-native/3.9.4-r0/image/home/build/ns3/poky/build/tmp/work/x86_64-linux/python-pycryptodomex-native/3.9.4-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/Cryptodome/init.py
tmp/work/x86_64-linux/python-pycryptodomex-native/3.9.4-r0/sysroot-destdir/home/build/ns3/poky/build/tmp/work/x86_64-linux/python-pycryptodomex-native/3.9.4-r0/recipe-sysroot-native/usr/lib/python2.7/site-packages/Cryptodome/init.py
tmp/sysroots-components/x86_64/python-pycryptodomex-native/usr/lib/python2.7/site-packages/Cryptodome/init.py

**Comment by kraj** [comment]
Can you create a patch for it ?

**Comment by RajeshRavi-brcm** [comment]
I posted the working patch in following thread, but github has misinterpreted it as formatting.
https://github.com/OP-TEE/optee_os/issues/3624
It did not allow me to attach patch file.
