### ISSUE TITLE
Hash for x264 appears to no longer be correct

### ISSUE THREAD

**Issue by dhylands** [openembedded/meta-openembedded#2]
I've been working with the Intel Galileo, which I think is using the dylan branch.

The meta-oe/recipes-multimedia/x264/x264_git.bb file contains:

SRCREV = "1cffe9f406cc54f4759fc9eeb85598fb8cae66c7"

which appears to no longer exist in the git.videolan.org repository. I found this tree on gitorious: https://gitorious.org/gxk-media/x264/commits/1cffe9f406cc54f4759fc9eeb85598fb8cae66c7 which has the correct hash, and by comparing the description, I was able to determine that the corresponding hash in the current git.videolan.org repository is c6bfcec47c9d1fff0489a30215501babea29f59c

I wasn't quite sure what the development procedure for this repo was, so I thought I would raise the issue and ask how to proceed.

I'm happy to do a pull request. I noticed that x264 doesn't seem to exist in the master branch, and I wasn't sure of the significance of that either.

**Comment by shr-project** [comment]
If the issue is still valid, then send a patch to openembedded-devel@lists.openembedded.org
