### ISSUE TITLE
nano changed license to GPLv3

### ISSUE THREAD

**Issue by frederiksdun** [openembedded/meta-openembedded#20]
according to http://svn.savannah.gnu.org/viewvc/trunk/nano/COPYING?revision=4147&root=nano&view=markup nano changed it's license to GPLv3 in 2007.

LIC_FILES_CHKSUM uses correct checksum, but LICENSE is set to GPLv2

**Comment by balister** [comment]
Please use openembedded-devel@lists.openembedded.org. We do not use
github tools.

**Comment by shr-project** [comment]
We don't use github.com for tracking issues.

If the issue is still valid, then send a patch to openembedded-devel@lists.openembedded.org
