### ISSUE TITLE
OpenLDAP: Libraries are not all installed on target

### ISSUE THREAD

**Issue by BrunoVernay** [openembedded/meta-openembedded#21]
There are no build error, but at runtime, OpenLDAP cannot load its modules.
Looking at the files, only some are installed on the target (file matching this regexp: `back_([a-z]*)\-.*\.so\..*$`)

Also libraries consistently (compilation, package, install) go to /usr/lib/openldap/openldap/ (twice "openldap").   Note that the files are build, but not installed.

I am using Jethro branch.

https://github.com/openembedded/meta-openembedded/blob/jethro/meta-oe/recipes-support/openldap/openldap_2.4.42.bb

**Comment by shr-project** [comment]
We don't use github.com for tracking issues.

If the issue is still valid, then send a patch to openembedded-devel@lists.openembedded.org
