### ISSUE TITLE
QT change in openembedded-core causes build failure

### ISSUE THREAD

**Issue by mdhorn** [openembedded/meta-openembedded#22]
If you attempt to build any project with which uses recipes from meta-openembedded/meta-oe, there are build errors due to QT changes in openembedded-core:

    ERROR: ParseError at /home/user/devel/meta-openembedded/meta-oe/recipes-navigation/monav/monav_0.3.bb:17: Could not inherit file classes/qmake2.bbclass
The problem line is

    inherit qmake2 qt4x11
due to the fact recipes-qt are no longer a part of the OE-core.

It appears that a recent commit to the openembedded-core project made changes to QT which are causing this build failure:

    commit cb89d2b25b4edb1241bc5426a69a6bc44df9be2c
    Author: Alexander Kanavin <alexander.kanavin@linux.intel.com>
    Date:   Fri Nov 27 15:48:20 2015 +0200
    
        qt4: remove recipes and classes
        
        Qt4 is no longer supportd upstream, but it is still needed for LSB compliancy.
        Qt4 recipes have been moved to a separate meta-qt4 layer to be consistent with
        meta-qt3 and meta-qt5.
    
        Signed-off-by: Alexander Kanavin <alexander.kanavin@linux.intel.com>
        Signed-off-by: Ross Burton <ross.burton@intel.com>

In addition to the monav recipe, several others in the meta-eo have dependencies on QT:

    ./meta-oe/recipes-extended/hplip/hplip_3.12.6.bb
    ./meta-oe/recipes-extended/sip/sip_4.16.4.bb
    ./meta-oe/recipes-devtools/python/python-pyqt_4.11.3.bb
    ./meta-oe/recipes-qt/qtserialport/qtserialport-e_5.1.0.bb
    ./meta-oe/recipes-qt/libconnman-qt/libconnman-qt_git.bb
    ./meta-oe/recipes-qt/libconnman-qt/libconnman-qte_git.bb
    ./meta-oe/recipes-qt/qconnman/qconnman-e_git.bb
    ./meta-oe/recipes-qt/qconnman/qconnman_git.bb
    ./meta-oe/recipes-qt/qt-mobility/qt-mobility-embedded_1.2.0.bb
    ./meta-oe/recipes-qt/qt-mobility/qt-mobility_1.2.0.inc
    ./meta-oe/recipes-qt/qt-mobility/qt-mobility-x11_1.2.0.bb
    ./meta-oe/recipes-qt/qextserialport/qextserialport_1.2rc.bb
    ./meta-oe/recipes-qt/fingerterm/fingerterm_1.0.2.bb
    ./meta-oe/recipes-qt/libqofono/libqofono_0.4.bb
    ./meta-oe/recipes-qt/qwt/qwt-e_6.0.1.bb
    ./meta-oe/recipes-qt/qwt/qwt_6.0.1.bb
    ./meta-oe/recipes-qt/qcanobserver/qcanobserver_svn.bb
    ./meta-oe/recipes-qt/qcanobserver/qcanobserver-socketcan_svn.bb
    ./meta-oe/recipes-qt/qt-creator/qt-creator_2.8.1.bb
    ./meta-oe/recipes-support/maliit/maliit-framework_git.bb
    ./meta-oe/recipes-support/maliit/maliit-plugins_git.bb
    ./meta-oe/recipes-support/poppler/poppler_0.37.0.bb
    ./meta-oe/recipes-navigation/monav/monav_0.3.bb
    ./meta-oe/recipes-navigation/navit/navit.inc
    ./meta-oe/recipes-navigation/gpsd/gpsd_3.14.bb
    ./meta-multimedia/recipes-multimedia/vlc/vlc_2.2.1.bb

Let me know if more information is need or some direction on how to resolve the problem.

**Comment by shr-project** [comment]
We don't use github.com for tracking issues.

Please subscribe to openembedded-devel ML and you'll see that I've sent patch for this last week (and added it to master-next) and it was merged to master today.
