### ISSUE TITLE
libmodbus_3.1.6.bb missing patch files

### ISSUE THREAD

**Issue by nobody93** [openembedded/meta-openembedded#225]
Hi,

Failed to build libmodbus_3.1.6.bb:
WARNING: libmodbus-3.1.6-r0 do_fetch: Failed to fetch URL file://f1eb4bc7ccb09cd8d19ab641ee37637f8c34d16d.patch

 Where to download following patch files?

SRC_URI += "file://f1eb4bc7ccb09cd8d19ab641ee37637f8c34d16d.patch \
        file://Fix-float-endianness-issue-on-big-endian-arch.patch \
        file://Fix-typo.patch"

Thank you.

**Comment by kraj** [comment]
I do not see such an error, are you using latest master ? perhaps provide more information might help us to understand the problem

**Comment by nobody93** [comment]
Thanks kraj, all good
