### ISSUE TITLE
python-periphery is missing python-mmap dependency on master

### ISSUE THREAD

**Issue by Urist-McGit** [openembedded/meta-openembedded#233]
I am building a minimal image with yocto and encountered this missing runtime dependency. Adding the dependency with `RDEPENDS_${PN} += ${PYTHON_PN}-mmap` solved the problem.

**Comment by kraj** [comment]
thanks you, I think this is a good fix, can you submit it as a pull request if possible ?

**Comment by kraj** [comment]
fixed with 95d7ee4a95761f2676e6819dee9b616224be777f
