### ISSUE TITLE
python3-redis recipe is missing dependencies

### ISSUE THREAD

**Issue by Bog999** [openembedded/meta-openembedded#236]
Hi, I tried to add python3-redis to my yocto (zeus) and when I try to do "import redis" I get the error ```ModuleNotFoundError: No module named 'hashlib'```
I think that the library should be added to the recipe as a dependency.

Edit:
Looks like the missing library is python3-cryptography

**Comment by kraj** [comment]
Please add that to `RDEPENDS_${PN}` and create a patch please

**Comment by Bog999** [comment]
#240

**Comment by Bog999** [comment]
I added a pull request for master-next #241

**Comment by kraj** [comment]
fixed with bf209dbf116a958689d82a73b7e1f4f1abfd5353
