### ISSUE TITLE
Changes to python "warehouse" causing pypi.bbclass to fail

### ISSUE THREAD

**Issue by markmevans** [openembedded/meta-openembedded#24]
[pypi issue #438](https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package) broke URL lookups for packages.  I believe the issues' resolution requires changing the domain used for the package's URL from:

`https://pypi.python.org`

to:

`https://files.pythonhosted.org`

```
--- pypi.bbclass
+++ pypi.bbclass
@@ -13,7 +13,7 @@ def pypi_src_uri(d):
     package = d.getVar('PYPI_PACKAGE', True)
     package_ext = d.getVar('PYPI_PACKAGE_EXT', True)
     pv = d.getVar('PV', True)
-    return 'https://pypi.python.org/packages/source/%s/%s/%s-%s.%s' % (package[0], package, package, pv, package_ext)
+    return 'https://files.pythonhosted.org/packages/source/%s/%s/%s-%s.%s' % (package[0], package, package, pv, package_ext)
 
 PYPI_SRC_URI ?= "${@pypi_src_uri(d)}"
```

Seems to work.

**Comment by graugans** [comment]
Have you already started a discussion on the mailing list about this? Because normally Patches are sent to the mailinglist instead of github pull requests.
