### ISSUE TITLE
Using meta-python with layer core

### ISSUE THREAD

**Issue by c-goes** [openembedded/meta-openembedded#246]
I'm trying to use meta-python from branch "dunfell" with the poky release tags/yocto-3.1

This error occurs when I try

````
ERROR: Layer 'meta-python' depends on version >= 12 of layer 'core', but version 11 is currently enabled in your configuration. Check that you are using the correct matching versions/branches of these two layers.
````

Do I need a specific version of meta-openembedded?

**Comment by shr-project** [comment]
You need recent version of openembedded-core layer as the error says. Upgrade to latest revision in dunfell branch as it's always recommended, instead of using tags/yocto-3.1.

**Comment by c-goes** [comment]
Thank you
