### ISSUE TITLE
Dunfell] fetch warning for enca

### ISSUE THREAD

**Issue by akuster** [openembedded/meta-openembedded#305]
WARNING: enca-1.9-r0 do_fetch: Failed to fetch URL http://www.sourcefiles.org/Networking/Tools/Miscellanenous/enca-1.9.tar.bz2, attempting MIRRORS if available

need to check other branches

**Comment by akuster** [comment]
same version in master.

SRC_URI is gone so found alt source.

**Comment by akuster** [comment]
patch sent

**Comment by akuster** [comment]
in master

https://git.openembedded.org/meta-openembedded/commit/?id=460077d30ffedca4c794f60cd0f21404fc1736d7

**Comment by kraj** [comment]
do we need it on dunfell/gatesgarth?

**Comment by akuster** [comment]
yes. on my list.
