### ISSUE TITLE
gatesgarth & Dunfell: qemx86 build failure on luajit

### ISSUE THREAD

**Issue by akuster** [openembedded/meta-openembedded#310]
I have been seeing this for awhile after switching to Ubuntu 20
https://errors.yoctoproject.org/Errors/Details/541244/

/usr/include/linux/errno.h:1:10: fatal error: asm/errno.h: No such file or directory
    1 | #include <asm/errno.h>
      |          ^~~~~~~~~~~~~

**Comment by kraj** [comment]
you need 32bit toolchain on build host. see https://github.com/openembedded/meta-openembedded/blob/master/meta-oe/README

**Comment by akuster** [comment]
cool. Ubuntu 20.05 needs
sudo apt-get install gcc-multilib

**Comment by kraj** [comment]
You can update the readme to include Ubuntu piece of you wish

**Comment by akuster** [comment]
patch sent.

**Comment by akuster** [comment]
in master. https://git.openembedded.org/meta-openembedded/commit/?id=973fe410d238e0c361f8bc4d9ba7915464217e22
