### ISSUE TITLE
Update SDL to current release

### ISSUE THREAD

**Issue by rzr** [openembedded/meta-openembedded#312]
According to upstream latest release of SDL version 2.0.14 (stable) 

https://www.libsdl.org/download-2.0.php

May it be also updated in master branch, current version is behind:
https://github.com/openembedded/openembedded-core/blob/master/meta/recipes-graphics/libsdl2/libsdl2_2.0.12.bb

I'll may submit a patch to catch up, unless anyone tell me if there is any reason stick to this version.

**Comment by kraj** [comment]
Please send an upgrade patch

**Comment by rzr** [comment]
can be closed, it was updated at:

https://github.com/openembedded/openembedded-core/commit/5b54e97594ab021a73d3225ed42dac0dfaf3fc15

I am tracking poky sync
