### ISSUE TITLE
Parse error: dunfell

### ISSUE THREAD

**Issue by oleorhagen** [openembedded/meta-openembedded#317]
```
bitbake core-image-full-cmdline
Parsing recipes...ERROR: ParseError at /builds/Northern.tech/Mender/yocto/build/../meta-openembedded/meta-oe/recipes-extended/libimobiledevice/libplist_2.1.0.bb:9: Could not inherit file classes/python3targetconfig.bbclass
```

As far as I can see, it was introduced [here](https://github.com/openembedded/meta-openembedded/commit/f60cbaf0429f96f0137c911937295a76806d821d). However, what the solution should be I do not know.

**Comment by oleorhagen** [comment]
@kraj @akuster What do you guys think of this?

**Comment by shr-project** [comment]
@oleorhagen you need to update to latest oe-core/dunfell.

**Comment by oleorhagen** [comment]
Thanks
