### ISSUE TITLE
Python Autobahn for Python2

### ISSUE THREAD

**Issue by jbleyel** [openembedded/meta-openembedded#341]
Please add Python Autobahn for Python2 too.
You need to use the tag 19.11.2
https://github.com/crossbario/autobahn-python/releases/tag/v19.11.2

Thanks

**Comment by shr-project** [comment]
Python2 is EOL, no new recipes will be added for it.

https://www.python.org/doc/sunset-python-2/
https://python3statement.org/

**Comment by shr-project** [comment]
Also see https://git.openembedded.org/meta-python2/commit/?id=619cbcf0fe1dbaeb6cdef93e8639822df173d02e

**Comment by kraj** [comment]
I think we can close this issue
