### ISSUE TITLE
oniguruma dependency broken 

### ISSUE THREAD

**Issue by Liu-He** [openembedded/meta-openembedded#35]
ERROR: onig-5.9.6-r0 do_fetch: Fetcher failure for URL: 'https://web.archive.org/web/20150807014439/http://www.geocities.jp/kosako3/oniguruma/archive/onig-5.9.6.tar.gz'. Unable to fetch URL from any source.
ERROR: onig-5.9.6-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/ubuntu/poky/build-mlb01-rtos/tmp/work/cortexa7-poky-linux-gnueabi/onig/5.9.6-r0/temp/log.do_fetch.68923
ERROR: Task (/home/ubuntu/poky/meta-openembedded/meta-oe/recipes-support/onig/onig_5.9.6.bb:do_fetch) failed with exit code '1'

The page can not be displayed
Sorry, the accessed page is no longer currently available. Please try again later. Please check the help If you have any questions, if that does not work please contact us from within the help page.

**Comment by shr-project** [comment]
We're not using github issues, almost nobody reads it here.

Use openembedded-devel@lists.openembedded.org as mentioned in meta-oe/README.
