### ISSUE TITLE
Branch name to "main"  in some recipies

### ISSUE THREAD

**Issue by kallmanjaa** [openembedded/meta-openembedded#377]
Some of the recipes source uri is changed from branch name=master to branch name=main. Please could you guys fix this in all branches. Because of this our ci build is failing for out yocto project.

**Comment by shr-project** [comment]
You should at least say which recipes are failing for you and your ci. All builds fine for me, but I have well populated premirror, so issues like this aren't detected by ci builds I'm running.

**Comment by kallmanjaa** [comment]
It is failing in the recipie ostree in recipies-extended in Zeus branch.
Actually we dint mirror the sources , but next time we would definitely do it.

**Comment by shr-project** [comment]
zeus is already EOL, see https://wiki.yoctoproject.org/wiki/Releases , you can easily fix ostree SRC_URI with local .bbappend and start planing to upgrade to newer release.
