### ISSUE TITLE
ExpansionError during parsing poky/meta-openembedded/meta-oe/recipes-support/zile/zile_2.4.11.bb

### ISSUE THREAD

**Issue by JOE-JOE-NGIGI** [openembedded/meta-openembedded#38]
I am on yocto poky version 2.2 morty branch and keep getting the above expansion error.
Anyone with an idea how I can go about it?

**Comment by shr-project** [comment]
It doesn't show the actual error and use ML mentioned in README not the github issues (almost nobody reads it here).
