### ISSUE TITLE
How to use meta-networking for configuring the DNS server

### ISSUE THREAD

**Issue by binary-nerd** [openembedded/meta-openembedded#39]
I am working on beaglebones.

With the default image provided for beaglebone green wireless devices, the moment the board is connected to the PC, USB interface(USB0) is generated and an IP address is assigned to it. And then we can `ssh` into the BBGW whose IP is statically configured(192.168.7.2).

I am working on yocto image for Beaglebone devices (https://github.com/jumpnow/meta-bbb). And I would like to have the same support.

I would like My BBGW to have a DNS server running which can Assign an IP address to the host systems USB0 interface.

I learnt that I have to use meta-networking layer for this purpose. meta-networking looks very big and I am not sure what components I need to take for my purposes. Any ideas will surely help me.

**Comment by shr-project** [comment]
Use mailing list mentioned in the README file.
