### ISSUE TITLE
Missing Licenses

### ISSUE THREAD

**Issue by jalanb** [openembedded/meta-openembedded#4]
meta-networking uses code covered by the following licenses, but the licenses are not found in https://github.com/openembedded/meta-openembedded/tree/master/meta-networking/licenses

* Carnegie Mellon University License, used by Cyrus-SASL
 * In particular clause 4 of that license is not being met, I cannot find the clause anywhere in the source tree
* Carnegie Mellon Language Technologies Institute License, used by Flite
* CURL License, used by code from libcurl
 * I'm not sure of how files are organized, but going on what I see: This patch file is within the directory recipes-support/curlpp (which is under MIT), but looks likes it is actually a patch for libcurl
 * I cannot find the libcurl code being patched within https://code.google.com/p/curlpp/downloads/detail?name=curlpp-0.7.3.tar.gz, so I assume it is separately downloaded for meta-networking.

**Comment by shr-project** [comment]
We don't use github.com for tracking issues.

If the issue is still valid, then send a patch to openembedded-devel@lists.openembedded.org

**Comment by jalanb** [comment]
I think the problem requires policy competence, not the kind of decision I can make in a patch. But, thanks for playing
