### ISSUE TITLE
Issue with xterm_325.bb Checksum

### ISSUE THREAD

**Issue by tlandle** [openembedded/meta-openembedded#40]
For some reason, the xterm_325.bb download produces a different checksum every single time it is fetched.

Logs to prove are below:
 xterm-325-r0 do_fetch: Fetcher failure for URL: 'http://invisible-mirror.net/archives/xterm/xterm-325.tgz'. Checksum mismatch!
**File: '/home/mca/BSP_2017.1/poky/build/../../bsp_downloads/xterm-325.tgz' has md5 checksum 9fc339a445a08b995e3c1f3b2ded1d00 when e78a0bbc4d5fa3780917e447ae8ebc6b was expected
File: '/home/mca/BSP_2017.1/poky/build/../../bsp_downloads/xterm-325.tgz' has sha256 checksum b5bbee8b416ea8b6050d2690780a6085d48bb12ca71f94f39d776916fc931bb7 when 3b31b07a0c40427e9330ec3be9d1a748c72808f945953cea9e526e48be315f1b was expected**
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[md5sum] = "9fc339a445a08b995e3c1f3b2ded1d00"
SRC_URI[sha256sum] = "b5bbee8b416ea8b6050d2690780a6085d48bb12ca71f94f39d776916fc931bb7"
Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.

ERROR: xterm-325-r0 do_fetch: Fetcher failure for URL: 'http://invisible-mirror.net/archives/xterm/xterm-325.tgz'. Unable to fetch URL from any source.
ERROR: xterm-325-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/mca/BSP_2017.1/poky/build/tmp/work/aarch64-poky-linux/xterm/325-r0/temp/log.do_fetch.6712
ERROR: Task (/home/mca/BSP_2017.1/poky/build/../../meta-openembedded/meta-oe/recipes-graphics/xorg-app/xterm_325.bb:do_fetch) failed with exit code '1'

ERROR: xterm-325-r0 do_fetch: Fetcher failure for URL: 'http://invisible-mirror.net/archives/xterm/xterm-325.tgz'. Checksum mismatch!
File: '/home/mca/BSP_2017.1/poky/build/../../bsp_downloads/xterm-325.tgz' has md5 checksum 222accddbcdf2ab8b9ca9e29ea50f8ea when f17951541559fe7f47deb2108e3b450d was expected
File: '/home/mca/BSP_2017.1/poky/build/../../bsp_downloads/xterm-325.tgz' has sha256 checksum a57d3cd4ead8ef1581b2ae1045f47eb53976853ce54760b13a9b30850e84d4af when 29b4db2882156c650dfd78d9fbe180825639336ea8e56253d9b9e9eea76ac3d6 was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[md5sum] = "222accddbcdf2ab8b9ca9e29ea50f8ea"
SRC_URI[sha256sum] = "a57d3cd4ead8ef1581b2ae1045f47eb53976853ce54760b13a9b30850e84d4af"
Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.

ERROR: xterm-325-r0 do_fetch: Fetcher failure for URL: 'http://invisible-mirror.net/archives/xterm/xterm-325.tgz'. Unable to fetch URL from any source.
ERROR: xterm-325-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/mca/BSP_2017.1/poky/build/tmp/work/aarch64-poky-linux/xterm/325-r0/temp/log.do_fetch.129332
ERROR: Task (/home/mca/BSP_2017.1/poky/build/../../meta-openembedded/meta-oe/recipes-graphics/xorg-app/xterm_325.bb:do_fetch) failed with exit code '1'

ERROR: xterm-325-r0 do_fetch: Fetcher failure for URL: 'http://invisible-mirror.net/archives/xterm/xterm-325.tgz'. Checksum mismatch!
File: '/home/mca/BSP_2017.1/poky/build/../../bsp_downloads/xterm-325.tgz' has md5 checksum f17951541559fe7f47deb2108e3b450d when 874b55c9d30637f8ea21abb7d6a16de2 was expected
File: '/home/mca/BSP_2017.1/poky/build/../../bsp_downloads/xterm-325.tgz' has sha256 checksum 29b4db2882156c650dfd78d9fbe180825639336ea8e56253d9b9e9eea76ac3d6 when 3098f4bff73fd5c08a14ffa0bb672ad87f008e2f506e591faeec5e6708396dc4 was expected
If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
SRC_URI[md5sum] = "f17951541559fe7f47deb2108e3b450d"
SRC_URI[sha256sum] = "29b4db2882156c650dfd78d9fbe180825639336ea8e56253d9b9e9eea76ac3d6"
Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.

ERROR: xterm-325-r0 do_fetch: Fetcher failure for URL: 'http://invisible-mirror.net/archives/xterm/xterm-325.tgz'. Unable to fetch URL from any source.
ERROR: xterm-325-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/mca/BSP_2017.1/poky/build/tmp/work/aarch64-poky-linux/xterm/325-r0/temp/log.do_fetch.120650
ERROR: Task (/home/mca/BSP_2017.1/poky/build/../../meta-openembedded/meta-oe/recipes-graphics/xorg-app/xterm_325.bb:do_fetch) failed with exit code '1'

Any idea of what is going on here? I reverted to xterm_320.bb and it worked just fine.

**Comment by shr-project** [comment]
We don't do issues on github as github is only read-only mirror, use ML mentioned in README:
https://github.com/openembedded/meta-openembedded/blob/master/meta-oe/README#L7
