### ISSUE TITLE
python pytz error fetching

### ISSUE THREAD

**Issue by ostende** [openembedded/meta-openembedded#41]
> ERROR: python-pytz-2017.2-r0 do_fetch: Fetcher failure for URL: 'https://files.pythonhosted.org/packages/source/p/pytz/pytz-2017.2.tar.gz'. Unable to fetch URL from any source.
ERROR: python-pytz-2017.2-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/ostende/e2/build-enviroment/builds/openbh/release/vusolo2/tmp/work/mips32el-oe-linux/python-pytz/python-pytz-2017.2-r0/temp/log.do_fetch.17425
ERROR: Task (/home/ostende/e2/build-enviroment/meta-openembedded/meta-python/recipes-devtools/python/python-pytz_2017.2.bb:do_fetch) failed with exit code '1'

**Comment by shr-project** [comment]
We don't do issues on github as github is only read-only mirror, use ML mentioned in README:
https://github.com/openembedded/meta-openembedded/blob/master/meta-oe/README#L7
