### ISSUE TITLE
GUI login prompt

### ISSUE THREAD

**Issue by JOE-JOE-NGIGI** [openembedded/meta-openembedded#49]
I successfully built a core-image-sato image using the pyro branch, for my cubieboard2. I would like to incorporate a login prompt on the display just before sato launches but I don't have a workaround for it. Anyone who's tried or has an idea?
My layers are:
1.meta
2.meta-poky
3.meta-openembedded/meta-gnome
4.meta-openembedded/meta-oe
5.meta-sunxi

**Comment by JOE-JOE-NGIGI** [comment]
Has anyone found a way to this?
I have lxdm in my system but does not start automatically. However when I run /etc/init.d/xserver-nodm stop
and then run lxdm, I get  a login prompt on the frame buffer.
1. How do I make lxdm run automatically once X is launched so that one only accesses the desktop after the login prompt?

**Comment by graugans** [comment]
@JOE-JOE-NGIGI please use the mailinglist for this kind of questions. This repo is just a mirror!
