### ISSUE TITLE
syntax error in meta-python/recipes-devtools/python/python3-fasteners_0.16.3.bb

### ISSUE THREAD

**Issue by pchand20** [openembedded/meta-openembedded#499]
seems there is some syntax error in meta-python/recipes-devtools/python/python3-fasteners_0.16.3.bb recipe 

here is syntax which is giving some error.
**RDEPENDS:${PN} += "**\
    ${PYTHON_PN}-logging \
    ${PYTHON_PN}-fcntl \
"
correct syntax working for me is following. also aligned with yocto manual. 

**RDEPENDS_${PN} += "\**
    ${PYTHON_PN}-logging \
    ${PYTHON_PN}-fcntl \
"

**Comment by shr-project** [comment]
See https://github.com/openembedded/meta-openembedded/pull/497 and update your bitbake revision.

**Comment by pchand20** [comment]
seems some latest version of bitbake needed for compatibility to parse new syntax. could not find exactly which version of bitbake have this support but some oct-9 commit on 1.4 works for me. closing it.

**Comment by shr-project** [comment]
https://github.com/ros/meta-ros/pull/902 linked from the other PR lists the exact commits where the compatibility was introduced.
