### ISSUE TITLE
Netperf SRC_URI link seems to be broken

### ISSUE THREAD

**Issue by helgeanl** [openembedded/meta-openembedded#50]
From what I can see in this [issue](https://github.com/HewlettPackard/netperf/issues/2) the ftp server for Netperf is closed down and all is moved to github. This causes the [netperf recipe](https://github.com/openembedded/meta-openembedded/blob/master/meta-networking/recipes-support/netperf/netperf_2.6.0.bb) in meta-networking to fail fetching.

**Comment by shr-project** [comment]
we use github only as read-only mirror, very few people ever read issues here.

You should send patch to openembedded-devel ML as README suggests.
