### ISSUE TITLE
Symless/synergy recipe points to bad repo (sources moved)

### ISSUE THREAD

**Issue by marina-tanco** [openembedded/meta-openembedded#54]
The synergy recipe points to a non-existent repository: the repo was moved some time ago, but now the sources have also been removed from the old location. Need support for this in the Morty branch, but note that even master branch is not updated.

meta-openembedded/meta-oe/recipes-support/synergy/synergy_git.bb

The new repository is at https://github.com/symless/synergy-core

**Comment by shr-project** [comment]
we use github only as read-only mirror, very few people ever read issues here.

You should send patch to openembedded-devel ML as README suggests.
