### ISSUE TITLE
polkit build break as libtool upgrade to 2.4.7

### ISSUE THREAD

**Issue by junzhuimx** [openembedded/meta-openembedded#555]
As libtool is upgraded from 2.4.6 to 2.4.7 on the poky master, the libtool meets the build break as:
| libtool: Version mismatch error.  This is libtool 2.4.7, but the
| libtool: definition of this LT_INIT comes from libtool 2.4.6.
| libtool: You should recreate aclocal.m4 with macros from libtool 2.4.7
| libtool: and run autoconf again.
| make[5]: *** [Makefile:494: pwd.lo] Error 63
| make[5]: *** Waiting for unfinished jobs....
| libtool: Version mismatch error.  This is libtool 2.4.7, but the
| libtool: definition of this LT_INIT comes from libtool 2.4.6.
| libtool: You should recreate aclocal.m4 with macros from libtool 2.4.7
| libtool: and run autoconf again.
| libtool: Version mismatch error.  This is libtool 2.4.7, but the
| libtool: definition of this LT_INIT comes from libtool 2.4.6.
| libtool: You should recreate aclocal.m4 with macros from libtool 2.4.7
| libtool: and run autoconf again.
| libtool: Version mismatch error.  This is libtool 2.4.7, but the
| libtool: definition of this LT_INIT comes from libtool 2.4.6.
| libtool: You should recreate aclocal.m4 with macros from libtool 2.4.7
| libtool: and run autoconf again.
| make[5]: *** [Makefile:494: grp.lo] Error 63
| make[5]: *** [Makefile:494: netgroup.lo] Error 63
| make[5]: *** [Makefile:494: netdb.lo] Error 63

**Comment by kraj** [comment]
https://github.com/openembedded/meta-openembedded/commit/97c904c765a860759d2320d6a67421ce1ecb705b fixed it.
