### ISSUE TITLE
Something wrong with libunwind URL in Yocto

### ISSUE THREAD

**Issue by JamesHagerman** [openembedded/meta-openembedded#6]
Hey guys,

I'm not sure if this is the right place to bring this issue up but until I have access to the Yocto dev mailing list, I have no other place to mention it.

When I run bitbake core-image-minimal in Yocto for the beaglebone while trying to use meta-oe, the Yocto scripts fail because they can not pull down libunwind. It says something about the URL being bad and kills the whole process.

Thanks for the help,
James

**Comment by shr-project** [comment]
We don't use github.com for tracking issues.

If the issue is still valid, then send a patch to openembedded-devel@lists.openembedded.org
