### ISSUE TITLE
kirkstone: ufw: do_compile ERROR: could not find required binary 'iptables'

### ISSUE THREAD

**Issue by howardcochran** [openembedded/meta-openembedded#610]
When building ufw on kirkstone, if the build host does not have iptables installed, the following error occurs:

> ERROR: ufw-0.36.1-r0 do_compile: 'python3 setup.py build ' execution failed.
> Log data follows:
> | DEBUG: Executing shell function do_compile
> | ERROR: could not find required binary 'iptables'
> | ERROR: 'python3 setup.py build ' execution failed.
> ERROR: Task ([snip]/meta-openembedded/meta-networking/recipes-connectivity/ufw/ufw_0.36.1.bb:do_compile) failed with exit code '1'

The problem is that the variables DISTUTILS_BUILD_ARGS and DISTUTILS_INSTALL_ARGS were not renamed to SETUPTOOLS_BUILD_ARGS and SETUPTOOLS_INSTALL_ARGS when this recipe was switched to use setuptools3_legacy instead of distutils earlier this year.

I have submitted a fix to `master` in PR #609 .  However, this needs to be added to the `kirkstone` branch also.  Thanks.

**Comment by kraj** [comment]
Applied to kirkstone too with eeeec7d
