### ISSUE TITLE
audit recipe is broken

### ISSUE THREAD

**Issue by embetrix** [openembedded/meta-openembedded#618]
@kraj 

the following commit is breaking any other recipes that has  PACKAGECONFIG with audit enabled : 
https://github.com/openembedded/meta-openembedded/commit/3a6f77e5166e4300071773a45187c7b01b87d119

since the following replace: 
`sed -i -e 's|#include <linux/audit.h>|#include "audit.h"|g' ${S}/lib/libaudit.h`

 but audit install the header in **/usr/include/linux/audit.h**

in my case I have meta-selinux enabled which activate by default  PACKAGECONFIG:append = "audit" on a lot of package.

**Comment by kraj** [comment]
Fixed with 4ff83dfb5a9f70188959814aa015910bd7363eca
