### ISSUE TITLE
Link errors (Yocto rocko) aufs-util 4.4

### ISSUE THREAD

**Issue by salerio-gs** [openembedded/meta-openembedded#68]
Not sure if this is the correct place to report this but here goes. I’m working on a custom distribution which uses the aufs-util recipe from the rocko version of meta-openembedded/meta-filesystems.

I have had trouble with the compilation step which I have tracked down to the use of the following poky include security_flags.inc located here: https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/conf/distro/include?h=rocko.

When this include is included in my distro aufs-util fails to compile with a link error “cannot find rcrt1.o: No such file or directory”, with the include excluded from the distro (which is the default situation) all is well.

**Comment by huypq6** [comment]
i received this error too, finding the solution. Any solution for it?

**Comment by floion** [comment]
You'd probably disable security flags:

> SECURITY_CFLAGS_pn-${PN} = "${SECURITY_NOPIE_CFLAGS}"

Like done here: https://github.com/resin-os/meta-resin/blob/master/meta-resin-sumo/recipes-utils/aufs-util/aufs-util_%25.bbappend
