### ISSUE TITLE
do_compile error with package mozjs

### ISSUE THREAD

**Issue by lamb0145** [openembedded/meta-openembedded#7]
My yocto program is from "https://wiki.linaro.org/HowTo/ARMv8/OpenEmbedded".

When I do "bitbake mozjs -f", I get a error below:

# bitbake mozjs -f
Loading cache: 100% |##########################################################################################################################| ETA:  00:00:00
Loaded 2418 entries from dependency cache.
WARNING: No recipes available for:
  /home/wkf/halogen/openembedded/jenkins-setup/meta-selinux/recipes-kernel/linux/linux-yocto_3.4.bbappend
  /home/wkf/halogen/openembedded/jenkins-setup/meta-virtualization/recipes-kernel/linux/linux-yocto_3.4.bbappend
  /home/wkf/halogen/openembedded/jenkins-setup/meta-selinux/recipes-extended/at/at_3.1.14.bbappend
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.23.1"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "SUSE-LINUX-11"
TARGET_SYS        = "aarch64-oe-linux"
MACHINE           = "genericarmv8"
DISTRO            = "nodistro"
DISTRO_VERSION    = "nodistro.0"
TUNE_FEATURES     = "aarch64"
meta-oe           
meta-filesystems  
meta-initramfs    
meta-webserver    
meta-networking   
meta-gnome        = "master:8c6721febfe1972c3bff6012ca7c70148343ec06"
meta-aarch64      
meta-bigendian    
meta-linaro       
meta-linaro-toolchain 
meta-linaro-integration = "master:a6d9587b06c8b513cf7013281a520e69fac99d72"
meta-virtualization = "master:4544c08af803f6ce569fd67216b33ee5e6c28cfa"
meta-browser      = "master:61cf2e04146c47be37d7652c8ecbfb47d66c52fb"
meta-selinux      = "master:fe356c16f803c01d57770ef4512c746517cabe95"
meta              = "master:ccf616b7263e446d5f0cd1169d84bfdcbc115f57"
meta-java         = "master:d2b75b615e4612f9fa05950c1d76d4a719e573d4"

NOTE: Preparing runqueue
NOTE: Tainting hash to force rebuild of task /home/wkf/halogen/openembedded/jenkins-setup/meta-openembedded/meta-oe/recipes-extended/mozjs/mozjs_17.0.0.bb, do_rm_work_all
WARNING: /home/wkf/halogen/openembedded/jenkins-setup/meta-openembedded/meta-oe/recipes-extended/mozjs/mozjs_17.0.0.bb.do_rm_work_all is tainted from a forced run
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
ERROR: Function failed: do_compile (log file is located at /home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/temp/log.do_compile.58030)
ERROR: Logfile of failure stored in: /home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/temp/log.do_compile.58030
Log data follows:
| DEBUG: SITE files ['endian-little', 'bit-64', 'arm-common', 'common-linux', 'common-glibc', 'aarch64-linux', 'common']
| DEBUG: Executing shell function do_compile
| NOTE: make -j 64
| make export
| make[1]: Entering directory `/home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/build'
| make -C config/ nsinstall
| mkdir -p /home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/build/.deps
| /usr/local/bin/python2.7 /home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/mozjs17.0.0/js/src/builtin/embedjs.py selfhosted.out.h /home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/mozjs17.0.0/js/src/js.msg \
| 	  /home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/mozjs17.0.0/js/src/builtin/macros.py /home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/mozjs17.0.0/js/src/builtin/array.js
| nsinstall.c
| make[2]: Entering directory `/home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/build/config'
| gcc -o host_nsinstall.o -c -O2 -pipe -g -feliminate-unused-debug-types -DXP_UNIX -O3 -DUNICODE -D_UNICODE  -I/home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/mozjs17.0.0/js/src/config -I. -I../dist/include         /home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/mozjs17.0.0/js/src/config/nsinstall.c
| pathsub.c
| gcc -o host_pathsub.o -c -O2 -pipe -g -feliminate-unused-debug-types -DXP_UNIX -O3 -DUNICODE -D_UNICODE  -I/home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/mozjs17.0.0/js/src/config -I. -I../dist/include         /home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/mozjs17.0.0/js/src/config/pathsub.c
| Traceback (most recent call last):
|   File "/home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/mozjs17.0.0/js/src/builtin/embedjs.py", line 12, in <module>
|     import re, sys, os, js2c, fileinput
|   File "/home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/mozjs17.0.0/js/src/builtin/js2c.py", line 36, in <module>
|     import bz2
| ImportError: No module named bz2
| make[1]: *** [selfhosted.out.h] Error 1
| make[1]: *** Waiting for unfinished jobs....
| gcc -o nsinstall -O2 -pipe -g -feliminate-unused-debug-types -DXP_UNIX -O3 -DUNICODE -D_UNICODE -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed host_nsinstall.o host_pathsub.o
| make[2]: Leaving directory `/home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/build/config'
| make[1]: Leaving directory `/home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/build'
| make: *** [default] Error 2
| ERROR: oe_runmake failed
| WARNING: /home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/temp/run.do_compile.58030:145 exit 1 from
|   exit 1
| ERROR: Function failed: do_compile (log file is located at /home/wkf/halogen/openembedded/jenkins-setup/build/tmp-eglibc/work/aarch64-oe-linux/mozjs/17.0.0-r0/temp/log.do_compile.58030)
ERROR: Task 6 (/home/wkf/halogen/openembedded/jenkins-setup/meta-openembedded/meta-oe/recipes-extended/mozjs/mozjs_17.0.0.bb, do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 675 tasks of which 657 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
  /home/wkf/halogen/openembedded/jenkins-setup/meta-openembedded/meta-oe/recipes-extended/mozjs/mozjs_17.0.0.bb, do_compile
Summary: There were 2 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by shr-project** [comment]
We don't use github.com for tracking issues.

If the issue is still valid, then send a patch to openembedded-devel@lists.openembedded.org
