### ISSUE TITLE
Cannot find nlohmann-json header files 

### ISSUE THREAD

**Issue by abs3n** [openembedded/meta-openembedded#747]
Hi, I was able to successfully install `meta-oe/recipes-devtools/nlohmann-json` by adding `IMAGE_INSTALL:append = " nlohmann-json"` in the `bblayers.conf` file , but for some reason, the rootfs image (`bitbake core-image-minimal`) does not have any header file under `/usr/include/nlohmann/*` when I checked by booting in qemu. Tried using ` find..  -name '*json.hpp*' ` , still no luck. 

Any leads would be appreciated!

**Comment by shr-project** [comment]
IIRC it's header only recipe, so all the files are installed in PN-dev package and PN is empty.

**Comment by abs3n** [comment]
Yes it is a header only, but apologies for my rookie knowledge in Yocto- when you say PN-dev, what exactly do you mean? I mean, for me to run a program that uses `nlohmann/json.hpp`, the header files need to exist in a location. So I was expecting the files to end up on rootfs under the standard header file path- `/usr/include/*`

**Comment by abs3n** [comment]
Never mind, just a freudian slip. Header only's are statically linked anyway, so I guess I should be fine with running my binary and do not even need to install `nlohmann-json` on target anyway.
