### ISSUE TITLE
Postinstall scriptlets of ['busybox'] have failed when trying to install apache2

### ISSUE THREAD

**Issue by FlaviuNistor** [openembedded/meta-openembedded#766]
Hello,

I am using kirkstone branch and I added apache2 in the list of recipes I want to install:
IMAGE_INSTALL:append = " apache2"

I have also added meta-openembedded/meta-webserver in build/conf/bblayers.conf.

The recipe works, but I get an error when do_rootfs is executed for my image.

do_rootfs: Postinstall scriptlets of ['busybox'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget:${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.

In the details error, I can see this:
update-alternatives: Error: not linking ....../rootfs/usr/sbin/httpd to /bin/busybox.nosuid since ...../rootfs/usr/sbin/httpd exists and is not a link

Am I forgetting something?

Thanks in advance,
Flaviu

**Comment by KorribanMaster** [comment]
Have you found a solution for this problem?

**Comment by FlaviuNistor** [comment]
Hello, 

yes I have found the correct way. Don't know if I can really call it a solution since the problem from my point of view is not caused either by apache or busybox recipe.

Look like that you can't have apache and httpd from busybox at the same time (busybox recipe will fail to create the simbolic link if httpd from apache is already part of rootfs).

My solution was to find where the busybox configuration got modified and httpd was enabled and remove this.

Maybe an extra check can be implemented and if httpd is already in the rootfs, the creation of the simbolic link can be skiped.

Thanks,
Flaviu
