### ISSUE TITLE
protobuf src_uri in rocko branch

### ISSUE THREAD

**Issue by varigigi** [openembedded/meta-openembedded#82]
Hi All.
it looks that 3.4.x branch has been removed from google github, making protobuf unbuidable.
Any chance to cherry-pick commit 01e54eb2fa5fb3e528781f51c85e79eb8c9b74d1 in rocko from sumo/master branch of meta-openembedded ?
Thansk
BR
Pier

**Comment by shr-project** [comment]
See https://patchwork.openembedded.org/patch/151242/
