### ISSUE TITLE
Broken php-fpm systemd service in kirkstone, mickledore and nanbield

### ISSUE THREAD

**Issue by bence98** [openembedded/meta-openembedded#822]
Commit 4cefe01 ("php-fpm: fix systemd") fixes php-fpm's systemd service. However, this was not backported to kirkstone and mickledore.

**Comment by bence98** [comment]
Since then, mickledore and nanbield seem to have gone EOL, and this issue was never fixed. Is there any plans to fix this in kirkstone, which is supposed to be LTS until 2026, or are we just supposed to stick the support up our own arse?

**Comment by shr-project** [comment]
What about reading README and sending backport request to ML?

**Comment by shr-project** [comment]
You should send the patch you want to backport to ML with [kirkstone] in subject like README says https://git.openembedded.org/meta-openembedded/tree/meta-oe/README?h=kirkstone#n21

**Comment by bence98** [comment]
Fixed in kirkstone as of 69d1121922be.
