### ISSUE TITLE
[meta-oe][scarthgap] openbox crashes on alt+tab with fullscreen app probably caused by newer glib-2.0

### ISSUE THREAD

**Issue by FederAndInk** [openembedded/meta-openembedded#837]
When alt tabbing from a fullscreen app (chromium), openbox crashes, this is apparently due to glib-2.0 upgrade (>= 2.76)

found related bug on arch: https://bugs.archlinux.org/task/77853

the commit on the openbox repo: https://github.com/Mikachu/openbox/commit/9ed6fdd71890c5cc43747f105382d5677e5d37e7

I haven't tried the patch yet, will report back when tried

**Comment by kraj** [comment]
Thanks for report @FederAndInk if this fixes the problem, it would be good to send a patch to openbox recipe to apply this patch

**Comment by FederAndInk** [comment]
Tried it, the patch fixes this issue, unfortunately I don't have the time to send the patch for now

**Comment by ycongal-smile** [comment]
@kraj @FederAndInk We will handle it from here and send a patch :)

**Comment by ycongal-smile** [comment]
Patch sent : https://lists.openembedded.org/g/openembedded-devel/topic/meta_oe_patch_openbox_fix/107168578

**Comment by ycongal-smile** [comment]
Merged in master : https://git.openembedded.org/meta-openembedded/commit/?id=85132c16210d1bdf83e8be5b3da4f430ce7b4b91

**Comment by kraj** [comment]
Thanks @ycongal-smile we can close this issue. Please re-open if something more is needed on this.
