### ISSUE TITLE
dbus-broker: no updates since langdale

### ISSUE THREAD

**Issue by FederAndInk** [openembedded/meta-openembedded#846]
dbus-broker hasn't been updated for a long time, I get a warning in the log with the current yocto kernel (will put it here when I get the chance)

I can send a patch when I have the time, but I don't know when.

**Comment by FederAndInk** [comment]
Linking this here: https://git.openembedded.org/meta-openembedded/commit/?id=b230d576bc977077af41b92c10311e5425a81b45

Nice :)

**Comment by kraj** [comment]
Lets close it as fixed
