### ISSUE TITLE
ERROR: Function failed: Fetcher failure for URL: 'git://risingtidesystems.com/lio-utils.git'. Unable to fetch URL from any source.

### ISSUE THREAD

**Issue by jk78346** [openembedded/meta-openembedded#88]
I can't find any other replacement of this URL, and after typing"bitbake fsl-image-minimal", it keeps saying that this is ERROR and stop.

any solution?

**Comment by kraj** [comment]
Please test the patch posted on master-next 

http://git.openembedded.org/meta-openembedded/log/?h=master-next

**Comment by kraj** [comment]
fixed with 3d33a2ecd6f8f776a7eb9cb41eabd15419725671
