### ISSUE TITLE
error

### ISSUE THREAD

**Issue by docea37** [openembedded/meta-openembedded#90]
hi 
error adress

`WARNING: lockdev-1.0.3+gitAUTOINC+16b899645d-r0 do_fetch: Failed to fetch URL git://anonscm.debian.org/lockdev/lockdev.git, attempting MIRRORS if available
Currently  4 running tasks (3547 of 15207)  23% |#######################                                                                             |
ERROR: lockdev-1.0.3+gitAUTOINC+16b899645d-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export SSH_AGENT_PID="1094"; export SSH_AUTH_SOCK="/run/user/1000/keyring/ssh"; export PATH="/home/oealliancebuilder/oealliance/build-enviroment/openembedded-core/scripts:/home/oealliancebuilder/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/lockdev/1.0.3+gitAUTOINC+16b899645d-r0/recipe-sysroot-native/usr/bin/arm-oe-linux-gnueabi:/home/oealliancebuilder/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/lockdev/1.0.3+gitAUTOINC+16b899645d-r0/recipe-sysroot/usr/bin/crossscripts:/home/oealliancebuilder/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/lockdev/1.0.3+gitAUTOINC+16b899645d-r0/recipe-sysroot-native/usr/sbin:/home/oealliancebuilder/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/lockdev/1.0.3+gitAUTOINC+16b899645d-r0/recipe-sysroot-native/usr/bin:/home/oealliancebuilder/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/lockdev/1.0.3+gitAUTOINC+16b899645d-r0/recipe-sysroot-native/sbin:/home/oealliancebuilder/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/lockdev/1.0.3+gitAUTOINC+16b899645d-r0/recipe-sysroot-native/bin:/home/oealliancebuilder/oealliance/build-enviroment/bitbake/bin:/home/oealliancebuilder/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/hosttools"; export HOME="/home/oealliancebuilder"; LANG=C git -c core.fsyncobjectfiles=0 clone --bare --mirror git://anonscm.debian.org/lockdev/lockdev.git /home/oealliancebuilder/oealliance/build-enviroment/sources/git2/anonscm.debian.org.lockdev.lockdev.git --progress failed with exit code 128, output:
Cloning into bare repository '/home/oealliancebuilder/oealliance/build-enviroment/sources/git2/anonscm.debian.org.lockdev.lockdev.git'...
fatal: unable to connect to anonscm.debian.org:
anonscm.debian.org[0: 194.177.211.202]: errno=Connection refused
anonscm.debian.org[1: 2001:648:2ffc:deb::211:202]: errno=Network is unreachable

ERROR: lockdev-1.0.3+gitAUTOINC+16b899645d-r0 do_fetch: Fetcher failure for URL: 'git://anonscm.debian.org/lockdev/lockdev.git'. Unable to fetch URL from any source.
ERROR: lockdev-1.0.3+gitAUTOINC+16b899645d-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/oealliancebuilder/oealliance/build-enviroment/builds/openatv/release/vuzero4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/lockdev/1.0.3+gitAUTOINC+16b899645d-r0/temp/log.do_fetch.22676
ERROR: Task (/home/oealliancebuilder/oealliance/build-enviroment/meta-openembedded/meta-oe/recipes-support/lockdev/lockdev_git.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3573 tasks of which 3518 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/oealliancebuilder/oealliance/build-enviroment/meta-openembedded/meta-oe/recipes-support/lockdev/lockdev_git.bb:do_fetch
Summary: There were 3 WARNING messages shown.
Summary: There were 3 ERROR messages shown, returning a non-zero exit code.
Makefile:886: recipe for target 'image' failed
make: *** [image] Error 1
`

**Comment by kraj** [comment]
do you still have this issue ? I can seem to reproduce it locally.

**Comment by kraj** [comment]
Can you test out [this](https://patchwork.openembedded.org/patch/157896/) patch and see if it helps you ?

**Comment by kraj** [comment]
Switched to tar version with 1ed152e32ec523c83bb05a4ae828c92fbb894acb which should fix this
