### ISSUE TITLE
php: host config leakage of HAS_VALGRIND

### ISSUE THREAD

**Issue by abaumfalk** [openembedded/meta-openembedded#94]
In the build process of php7.2.7 there seems to be a host configuration leakage to the target build.
I have installed valgrind on my build host and the php target build fails with:

.../build/tmp/work/core2-32-poky-linux/php/7.2.7-r0/php-7.2.7/sapi/cgi/cgi_main.c:100:11: fatal error: valgrind/callgrind.h: No such file or directory
|  # include "valgrind/callgrind.h"
|            ^~~~~~~~~~~~~~~~~~~~~~
| compilation terminated.
| make: *** [sapi/cgi/cgi_main.lo] Error 1
| make: *** Waiting for unfinished jobs....
| ERROR: oe_runmake failed
| WARNING: .../build/tmp/work/core2-32-poky-linux/php/7.2.7-r0/temp/run.do_compile.7658:1 exit 1 from 'exit 1'
| ERROR: Function failed: do_compile (log file is located at .../build/tmp/work/core2-32-poky-linux/php/7.2.7-r0/temp/log.do_compile.7658)
ERROR: Task (.../build/../meta-openembedded/meta-oe/recipes-devtools/php/php_7.2.7.bb:do_compile) failed with exit code '1'

When I remove valgrind from my host system, the build runs fine.

Checking the php source code I found that HAS_VALGRIND seems to be defined when the build fails, although there is no valgrind installed on the host.

I have seen this problem on the most recent sumo branch of meta-openembedded.

If I can add more information, please let me know!

**Comment by fmhess** [comment]
I have hit this same problem building angstrom sumo.  Anyone know how to manually tell php config not to use valgrind?

**Comment by fmhess** [comment]
found more info on the php problem here:

http://patchwork.ozlabs.org/patch/872168/
