### ISSUE TITLE
Bad license in srecord

### ISSUE THREAD

**Issue by megahallon** [openembedded/meta-openembedded#96]
srecord_1.64.bb is marked as GPLv2 while license file in tar ball is GPLv3

**Comment by kraj** [comment]
Thats right please test

http://git.openembedded.org/meta-openembedded-contrib/commit/?h=yoe/mut&id=53742385ee50a7d558c186e36cd2e2362423c7ca

**Comment by kraj** [comment]
fixed with e0d9dd2acdf34e87ca7b527497c41eb4e4e4db56
